### PR TITLE
Make Shy Posts translatable, load_plugin_textdomain

### PR DESCRIPTION
**Pull request by neverything**
Hi Topher, thanks for this plugin. It's almost what I need in a current change request for a client project.

In order to allow translations to be created and actually being loaded, I added a `.pot` file and added a method to `load_plugin_textdomain`. Additionally I added a `composer.json` file and bumped the version and stable tag.

Would love for you to review my changes and create a new release on w.org if all is set, or let me know if the pull request needs more work.

### CODE REVIEW

**Comment by swissspidy** [comment]
Note that a `.pot` file is not needed when the plugin is being hosted on WordPress.org. GlotPress will automatically create one there, and allow translations being edited via translate.wordpress.org.

**Comment by neverything** [comment]
Thanks @swissspidy removed the `.pot` file.

**Comment by neverything** [comment]
@topher1kenobe any chance you'll get to this anytime or did you abandon the plugin?

**Comment by topher1kenobe** [comment]
@neverything for some reason I never got notified of your notes! I'm in favor of merging, I'll review.

**Review by topher1kenobe — COMMENTED** [review]
Can you update the docblock to properly reflect the access type?

**Review by topher1kenobe — COMMENTED** [review]
Should the text domain be shyposts like you have, or should it be shy-posts to match the slug?

**Comment by neverything** [comment]
Thanks for your reply @topher1kenobe, will refresh the PR tomorrow or during the weekend.

- [ ] Update the doc block to show proper access type
- [ ] Re-think and maybe change textdomain to reflect plugin slug

**Comment by swissspidy** [comment]
Yep, the text domain should match the slug, i.e. `shy-posts`.

**Comment by topher1kenobe** [comment]
@neverything I'm getting @swissspidy 's notes in my email, but not yours.  When you're ready again, email me directly at topher@derosia.com

**Comment by neverything** [comment]
@topher1kenobe PR refreshed, email sent, thx!

**Comment by swissspidy** [comment]
@topher1kenobe ping! :)

**Comment by grappler** [comment]
@topher1kenobe Do you think you could have a look at this? We are still using this fork?

**Comment by topher1kenobe** [comment]
@neverything sorry this took so long to happen. I'll work on getting it on .org

**Pull request merged**
